RiiFood/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main
from main.views import show_main, create_product
from main.views import show_main, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id

from main.views import register 
# from main.views import login_user
from main.views import logout_user

from main.views import add_stock
from main.views import delete_product
from main.views import subtract_stock
from main.views import edit_product

from main.views import get_product_json
from main.views import add_product_ajax, add_ajax, remove_ajax, remove_all_ajax, create_product_flutter, get_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    # path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add-stock/<int:product_id>/', add_stock, name='add_stock'),
    path('delete-product/<int:product_id>/', delete_product, name='delete_product'),
    path('subtract-stock/<int:product_id>/', subtract_stock, name='subtract_stock'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('add-ajax/', add_ajax, name='add_ajax'),
    path('remove-ajax/', remove_ajax, name='remove_ajax'),
    path('remove-all-ajax/', remove_all_ajax, name='remove_all_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('get-flutter/', get_flutter, name='get_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    amount = models.IntegerField()
    description = models.TextField()
    price = models.IntegerField()
    gambar = models.URLField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        # fields = ["gambar","name", "price", "stok", "description"]
        fields = ['name', 'amount', 'description', 'price', 'gambar']

main/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.http import HttpResponse
from django.core import serializers

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def show_main(request):
    if 'last_login' not in request.COOKIES:
        return redirect("main:login")
    products = Product.objects.filter(user=request.user)
    item = Product.objects.filter(user=request.user)
    banyak_item = len(item)

    context = {
        'nama' : request.user,
        'class' : 'PBP B',
        'products': products,
        'banyak_item': banyak_item,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

# def login_user(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             response = HttpResponseRedirect(reverse("main:show_main")) 
#             response.set_cookie('last_login', str(datetime.datetime.now()))
#             return response
#         else:
#             messages.info(request, 'Sorry, incorrect username or password. Please try again.')
#     context = {}
#     return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_stock(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        action = request.POST.get('action')
        if action == 'add':
            product.amount += 1
        elif action == 'subtract':
            if product.amount > 0:
                product.amount -= 1
        product.save()

    return HttpResponseRedirect(reverse('main:show_main'))

def subtract_stock(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST' and product.amount > 0:
        product.amount -= 1
        product.save()

    return HttpResponseRedirect(reverse('main:show_main'))

def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_main'))


def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        gambar = request.POST.get("gambar")
        amount = request.POST.get("amount")
        user = request.user

        new_product = Product(name=name, price=price, description=description, gambar=gambar, amount=amount, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def add_ajax(request):
    if request.method == 'POST':
        id = request.POST.get("id")
        try:
            product = Product.objects.get(pk=id)
            product.amount += 1
            product.save()
            return HttpResponse(status=201)  # Status CREATED
        except Product.DoesNotExist:
            return HttpResponseNotFound("Product not found")

    return HttpResponseNotFound()

@csrf_exempt
def remove_ajax(request):
    if request.method == 'POST':
        id = request.POST.get("id")
        try:
            product = Product.objects.get(pk=id)
            product.amount -= 1
            product.save()
            if product.amount <= 0:
                product.delete()
            return HttpResponse(status=201)  # Status CREATED
        except Product.DoesNotExist:
            return HttpResponseNotFound("Product not found")

    return HttpResponseNotFound()

@csrf_exempt
def remove_all_ajax(request):
    if request.method == 'POST':
        id = request.POST.get("id")
        try:
            product = Product.objects.get(pk=id)
            product.delete()
            return HttpResponse(status=201)  # Status CREATED
        except Product.DoesNotExist:
            return HttpResponseNotFound("Product not found")

    return HttpResponseNotFound()


@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@login_required
def get_flutter(request):
    Produk = Product.objects.filter(user=request.user)
    return JsonResponse(serializers.serialize('json', Produk), content_type="application/json")

main/templates/create_product.html
{% extends 'base.html' %}

{% block content %}
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        border: 1px solid #ccc;
        padding: 20px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        background-color: #f4e8d5;
    }

    form {
        width: 50%;
    }

    h1 {
        text-align: center;
    }

    table {
        width: 100%;
    }

    table tr {
        margin-bottom: 10px;
    }

    table td {
        padding: 5px;
    }

    input[type="submit"] {
        background-color: #301c05;
        color: #fff;
        border: none;
        padding: 10px 20px;
        cursor: pointer;
        width: 100%;
    }

    input[type="submit"]:hover {
        background-color: #f6d5b9;
    }

    
</style>

<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h1>Add New Product</h1>
        <table>
            {{ form.as_table }}
            <tr>
                <td colspan="2">
                    <input type="submit" value="Add Product" />
                </td>
            </tr>
        </table>
    </form>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    body {
        background-color: #f4e8d5; 
        margin: 0;
        padding: 0;
    }

    h1 {
        font-size: 24px;
        text-align: center;
        margin-bottom: 20px;
    }

    h1#edit-product-title {
        font-family: 'Algerian', serif; 
    }

    form {
        width: 40%;
        margin: 0 auto;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    table, th, td {
        border: 2px solid #422b0a; 
    }

    th, td {
        padding: 15px; 
    }

    input[type="text"], input[type="number"], select {
        width: 100%;
        padding: 8px;
        margin: 5px 0;
        border: 1px solid #ccc; 
        border-radius: 4px;
    }

    input[type="submit"] {
        background-color: #4d2b08;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        width: 50%;
        margin: 1 auto;
    }

    input[type="submit"]:hover {
        background-color: #fad596;
    }
</style>

<h1 id="edit-product-title">Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>
{% endblock %}

main/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        body, html {
            margin: 0;
            padding: 0;
        }

        .login {
            width: 300px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f4e8d5;
            border-radius: 5px;
            text-align: center;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
            position: absolute; 
            top: 50%; 
            left: 50%;
            transform: translate(-50%, -50%); 
        }

        .login h1 {
            margin-bottom: 20px;
            color: #333;
        }

        form table {
            width: 100%;
        }

        form table td {
            padding: 10px;
        }

        form input[type="text"],
        form input[type="password"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #3a2b1a;
            border-radius: 3px;
        }

        .login_btn {
            background-color: #2a1c08;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            cursor: pointer;
        }

        .login_btn:hover {
            background-color: #f7be6e;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        ul li {
            color: red;
        }

        a {
            color: #007BFF;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="login">
        <h1>Login</h1>
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        
        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
    </div>
</body>
</html>

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<style>
    table {
        border-collapse: collapse;
        width: 70%; 
        margin: 0 auto;
    }

    th, td {
        border: 2px solid #392004;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #ddbe91;
    }

    h1, .nav-link {
        color: #FFFFFF;
    }

    h1, .navbar-brand {
        color: #e9b085; 
    }

    table tr:last-child {
        background-color: #ae7338; /* Bonus */
    }

    .custom-card .card-body,
    .custom-card .list-group-item {
        background-color: #ffcf90;
    }

    .card-img-top {
        max-width: 100%;
        height: auto;
    }

</style>


<div style="background-color: #fce5c5;">
    <h1 style="font-family: 'Broadway', serif; text-align: center; color: #341e01;">RiiFood</h1>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #462f05 !important">
        <div class="container-fluid">
        <a class="navbar-brand" href="#">RiiFood</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <!-- <a class="nav-link active" aria-current="page" href="#">Username : {{nama}}</a> -->
            <!-- <a class="nav-link" href="{% url 'main:create_product' %}">Add New Product</a> -->
            <a class="nav-link" href="{% url 'main:logout' %}">Logout</a>
            </div>
        </div>
        </div>
    </nav>
    <hr />
    <h5>Hallo {{ nama }}, Selamat Datang di RiiFood!</h5>
    <p>Nama : {{ nama }}</p>
    <p>Kelas : {{ class }}</p>
    <p>Kamu menyimpan {{ banyak_item }} item pada aplikasi ini </p>

    <div class="row" id="product_cards"></div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="gambar" class="col-form-label">Image URL:</label>
                            <input type="text" class="form-control" id="gambar" name="gambar" required></input>
                        </div>
                        <div class="mb-3">
                            <label for="amount" class="col-form-label">Stock:</label>
                            <input type="number" class="form-control" id="amount" name="amount" required></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>
    
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background-color: #442509;">Add Product by AJAX</button>


    <script>
        async function getProducts() {
            return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            const productCards = document.getElementById("product_cards");
            productCards.innerHTML = ""; // Clear existing cards
            const products = await getProducts();

            products.forEach((item) => {
                const card = `
                <div class="col-lg-4 col-md-6 mb-4">
                    <div class="card h-100 custom-card"> 
                        <img src="${item.fields.gambar}" class="card-img-top" alt="${item.fields.name}">
                        <div class="card-body">
                            <h5 class="card-title">${item.fields.name}</h5>
                            <p class="card-text">${item.fields.description}</p>
                            <a href="#" class="btn btn-primary" onclick="addItemAmount(${item.pk})" style="background-color: #392004;">+</a>
                            <a href="#" class="btn btn-primary" onclick="removeItemAmount(${item.pk})" style="background-color: #392004;">-</a>
                            <a href="#" class="btn btn-primary" onclick="removeItem(${item.pk})" style="background-color: #392004;">Hapus</a>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Price: ${item.fields.price}</li>
                            <li class="list-group-item">Stok: ${item.fields.amount}</li>
                            <li class="list-group-item">Date Added: ${item.fields.date_added}</li>

                        </ul>
                    </div>
                </div>
                `;

                productCards.insertAdjacentHTML("beforeend", card);
            });
        }

        refreshProducts();


        function addProduct() {
            fetch("{% url 'main:add_product_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshProducts)

            document.getElementById("form").reset()
            return false
        }
        document.getElementById("button_add").onclick = addProduct


        async function addItemAmount(pk) {
            const formData = new FormData();
            formData.append("id", pk);
            fetch("{% url 'main:add_ajax' %}", {
                method: "POST",
                body: formData
            }).then(() => {
                // Setelah berhasil menambah item, perbarui tampilan produk
                refreshProducts();
            });
        }

        async function removeItemAmount(pk) {
            const formData = new FormData();
            formData.append("id", pk);
            fetch("{% url 'main:remove_ajax' %}", {
                method: "POST",
                body: formData
            }).then(() => {
                // Setelah berhasil menghapus item, perbarui tampilan produk
                refreshProducts();
            });
        }

        async function removeItem(pk) {
            const formData = new FormData();
            formData.append("id", pk);
            fetch("{% url 'main:remove_all_ajax' %}", {
                method: "POST",
                body: formData
            }).then(() => {
                // Setelah berhasil menghapus semua item, perbarui tampilan produk
                refreshProducts();
            });
        }


    </script>


<h7>Sesi terakhir login: {{ last_login }}</h7>

<br />
</div>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        margin: 0;
    }
   
    .login {
        width: 750px; 
        margin: 0 auto;
        padding: 20px;
        background-color: #f4e8d5;
        border: 1px solid #281b03;
        border-radius: 5px;
    }

    .login h1 {
        text-align: center;
        margin-bottom: 20px;
    }

    /* Gaya untuk tabel formulir */
    .login form table {
        width: 120%;
    }

    .login form table tr {
        margin-bottom: 10px;
    }

    .login form table td {
        padding: 5px;
    }

    /* Gaya untuk tombol Daftar */
    .login form input[type="submit"] {
        background-color: #462506;
        color: #ffffff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }

    .login form input[type="submit"]:hover {
        background-color: #b8916c;
    }

    .login ul {
        list-style-type: none;
        padding: 0;
    }

    .login ul li {
        color: #e74c3c;
        margin: 5px 0;
    }

        /* Gaya untuk kotak input */
    .login form input[type="text"],
    .login form input[type="password"],
    .login form input[type="email"] {
        background-color: #fedeb3; 
        padding: 5px;
        border: 1px solid #ccc;
        border-radius: 3px;
    }

    /* Gaya saat input mendapat fokus */
    .login form input[type="text"]:focus,
    .login form input[type="password"]:focus,
    .login form input[type="email"]:focus {
        background-color: #ffe3c1; 
        outline: none;
    }

</style>

<div class="login">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td><input type="submit" name="submit" value="Daftar" /></td>
            </tr>
        </table>
    </form>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock content %}